name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - pydot
  - graphviz
  - numpy==1.14.0
  - pandas==0.22.0
  - tensorflow
  - Keras==2.2.2
  - ipython==6.5.0
  - scikit-learn
